about/urls.py
from django.urls import path
from . import views
app_name = 'about'

urlpatterns = [
    path('', views.about, name='about'),
    # path('team/', views.team, name='team')
]

accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register')
]

blog/api/urls.py
from django.urls import path
from .views import CommentListAPIView
app_name = 'blog'
urlpatterns = [
    path('', CommentListAPIView.as_view(), name='list')
]

blog/urls.py
from django.urls import path
from .views import Blog, BlogList, BlogDetail, CommentList
from . import views
app_name = 'blog'
urlpatterns = [
    path('', BlogList.as_view(), name='blog'),
    path('<int:pk>', BlogDetail.as_view(), name='detail'),
    path('comment-form/', views.comment_form),
    path('comments/', CommentList.as_view(), name='comments')
]

contact/urls.py
from django.urls import path
from . import views
app_name = 'contact'

urlpatterns = [
path('', views.contact, name='contact')
]

leramiz/urls.py
from django.contrib import admin
from django.urls import path, include
from about.views import index
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('about/', include('about.urls', namespace='about')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('api/', include('blog.api.urls', namespace='comment-api')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('featured-listing/', include('featured_listing.urls', namespace='featured_listing')),
    path('search/', include('search.urls', namespace='search')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from .views import SearchListView
app_name = 'search'
urlpatterns = [
    path('', SearchListView.as_view(), name='query')

]

blog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Blog(models.Model):
    blog_image = models.ImageField(upload_to="img/blog")
    author = models.CharField(max_length=150)
    blog_time = models.DateTimeField()
    blog_headline = models.CharField(max_length=300, default=None)
    blog_article = models.TextField(blank=True)
    article_highlight = models.TextField(blank=True)

    def __str__(self):
        return self.blog_headline

    def get_absolute_url(self):
        return reverse(viewname='blog:detail', kwargs={'pk':self.pk})


    #for comments
class CommentModel(models.Model):
    author = models.CharField(max_length=150)
    comment = models.TextField(blank=True)

    def __str__(self):
        return self.author + " : " + self.comment

blog/forms.py
from django import forms

class Comments(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Your Name"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Your Email"}))
    comment = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"Comments"}))

blog/api/views.py
from rest_framework import generics
from blog.models import CommentModel
from .serializers import CommentModelSerializer
class CommentListAPIView(generics.ListAPIView):
    serializer_class = CommentModelSerializer
    def get_queryset(self):
        return CommentModel.objects.all()

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from blog.models import Blog
from .forms import Comments
from .models import CommentModel
# Create your views here.
class BlogList(ListView):
    model = Blog
    template_name = "blog/blog.html"

class BlogDetail(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"

def comment_form(request):
    form = Comments(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data.get('name')
        email = form.cleaned_data.get('email')
        comment = form.cleaned_data.get('comment')
        comment_new = CommentModel(author=name, comment=comment)
        comment_new.save()
        print(name, " ", email, "", comment)
    context = {'form': form}
    return render(request, "blog/comment_form.html", context=context)

class CommentList(ListView):
    model = CommentModel
    template_name = "blog/comments.html"

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
	<title>LERAMIZ - Landing Page Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="LERAMIZ Landing Page Template">
	<meta name="keywords" content="LERAMIZ, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
{%block body%}
	 <!--Page Preloder-->
	<!--<div id="preloder">-->
		<!--<div class="loader"></div>-->
	<!--</div>-->

	 <!-- Header section  -->
	 <!-- Hero section -->
	 <!-- Filter form section -->
	<!-- Properties section -->
	<!-- Services section -->
	<!-- feature section -->
	<!-- feature category section -->
	<!-- Gallery section -->
	<!-- Review section -->
	<!-- Blog section -->
	<!-- Clients section -->
	<!-- Footer section -->
{% endblock %}
	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/map.js' %}"></script>
	<script src="{% static 'js/map-2.js' %}"></script>

	{% block script %}
	{% endblock %}

</body>
</html>

templates/blog.html
{% load static %}
<!-- Blog section -->
	<section class="blog-section spad">
		<div class="container">
			<div class="section-title text-center">
				<h3>LATEST NEWS</h3>
				<p>Real estate news headlines around the world.</p>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6 blog-item">
					<img src="{% static 'img/blog/1.jpg' %}" alt="">
					<h5><a href="single-blog.html">Housing confidence hits record high as prices skyrocket</a></h5>
					<div class="blog-meta">
						<span><i class="fa fa-user"></i>Amanda Seyfried</span>
						<span><i class="fa fa-clock-o"></i>25 Jun 201</span>
					</div>
					<p>Integer luctus diam ac scerisque consectetur. Vimus dotnetact euismod lacus sit amet. Aenean interdus mid vitae maximus...</p>
				</div>
				<div class="col-lg-4 col-md-6 blog-item">
					<img src="{% static 'img/blog/2.jpg' %}" alt="">
					<h5><a href="single-blog.html">Taylor Swift is selling her $2.95 million Beverly Hills mansion</a></h5>
					<div class="blog-meta">
						<span><i class="fa fa-user"></i>Amanda Seyfried</span>
						<span><i class="fa fa-clock-o"></i>25 Jun 201</span>
					</div>
					<p>Integer luctus diam ac scerisque consectetur. Vimus dotnetact euismod lacus sit amet. Aenean interdus mid vitae maximus...</p>
				</div>
				<div class="col-lg-4 col-md-6 blog-item">
					<img src="{% static 'img/blog/3.jpg' %}" alt="">
					<h5><a href="single-blog.html">NYC luxury housing market saturated with inventory, says celebrity realtor</a></h5>
					<div class="blog-meta">
						<span><i class="fa fa-user"></i>Amanda Seyfried</span>
						<span><i class="fa fa-clock-o"></i>25 Jun 201</span>
					</div>
					<p>Integer luctus diam ac scerisque consectetur. Vimus dotnetact euismod lacus sit amet. Aenean interdus mid vitae maximus...</p>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog section end -->

templates/clients.html
{% load static %}
<!-- Clients section -->
	<div class="clients-section">
		<div class="container">
			<div class="clients-slider owl-carousel">
				<a href="#">
					<img src="{% static 'img/partner/1.png' %}" alt="">
				</a>
				<a href="#">
					<img src="{% static 'img/partner/2.png' %}" alt="">
				</a>
				<a href="#">
					<img src="{% static 'img/partner/3.png' %}" alt="">
				</a>
				<a href="#">
					<img src="{% static 'img/partner/4.png' %}" alt="">
				</a>
				<a href="#">
					<img src="{% static 'img/partner/5.png' %}" alt="">
				</a>
			</div>
		</div>
	</div>
	<!-- Clients section end -->

templates/feature.html
{% load static %}
<!-- feature section -->
	<section class="feature-section spad">
		<div class="container">
			<div class="section-title text-center">
				<h3>Featured Listings</h3>
				<p>Browse houses and flats for sale and to rent in your area</p>
			</div>
			<div class="row">
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/1.jpg'%}" style="background-image: url('{% static 'img/feature/1' %}')">
							<div class="sale-notic">FOR SALE</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>1963 S Crescent Heights Blvd</h5>
								<p><i class="fa fa-map-marker"></i> Los Angeles, CA 90034</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 800 Square foot</p>
										<p><i class="fa fa-bed"></i> 10 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 2 Garages</p>
										<p><i class="fa fa-bath"></i> 6 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Tony Holland</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 1 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$1,200,000</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/2.jpg' %}">
							<div class="sale-notic">FOR SALE</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>305 North Palm Drive</h5>
								<p><i class="fa fa-map-marker"></i> Beverly Hills, CA 90210</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 1500 Square foot</p>
										<p><i class="fa fa-bed"></i> 16 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 2 Garages</p>
										<p><i class="fa fa-bath"></i> 8 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Gina Wesley</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 1 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$4,500,000</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/3.jpg' %}">
							<div class="rent-notic">FOR Rent</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>305 North Palm Drive</h5>
								<p><i class="fa fa-map-marker"></i> Beverly Hills, CA 90210</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 1500 Square foot</p>
										<p><i class="fa fa-bed"></i> 16 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 2 Garages</p>
										<p><i class="fa fa-bath"></i> 8 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Gina Wesley</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 1 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$2,500/month</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/4.jpg' %}">
							<div class="sale-notic">FOR SALE</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>28 Quaker Ridge Road, Manhasset</h5>
								<p><i class="fa fa-map-marker"></i> 28 Quaker Ridge Road, Manhasset</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 1200 Square foot</p>
										<p><i class="fa fa-bed"></i> 12 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 3 Garages</p>
										<p><i class="fa fa-bath"></i> 8 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Sasha Gordon </p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 8 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$5,600,000</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/5.jpg' %}">
							<div class="rent-notic">FOR Rent</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>Sofi Berryessa 750 N King Road</h5>
								<p><i class="fa fa-map-marker"></i> San Jose, CA 95133</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 500 Square foot</p>
										<p><i class="fa fa-bed"></i> 4 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 1 Garages</p>
										<p><i class="fa fa-bath"></i> 2 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Gina Wesley</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 8 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$1,600/month</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4 col-md-6">
					<!-- feature -->
					<div class="feature-item">
						<div class="feature-pic set-bg" data-setbg="{% static 'img/feature/6.jpg' %}">
							<div class="sale-notic">FOR SALE</div>
						</div>
						<div class="feature-text">
							<div class="text-center feature-title">
								<h5>1203 Orren Street, Northeast</h5>
								<p><i class="fa fa-map-marker"></i> Washington, DC 20002</p>
							</div>
							<div class="room-info-warp">
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-th-large"></i> 700 Square foot</p>
										<p><i class="fa fa-bed"></i> 7 Bedrooms</p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-car"></i> 1 Garages</p>
										<p><i class="fa fa-bath"></i> 7 Bathrooms</p>
									</div>
								</div>
								<div class="room-info">
									<div class="rf-left">
										<p><i class="fa fa-user"></i> Sasha Gordon </p>
									</div>
									<div class="rf-right">
										<p><i class="fa fa-clock-o"></i> 8 days ago</p>
									</div>
								</div>
							</div>
							<a href="#" class="room-price">$1,600,000</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- feature section end -->

templates/feature_category.html
{% load static %}
<!-- feature category section -->
	<section class="feature-category-section spad">
		<div class="container">
			<div class="section-title text-center">
				<h3>LOOKING PROPERTY</h3>
				<p>What kind of property are you looking for? We will help you</p>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6 f-cata">
					<img src="{% static 'img/feature-cate/1.jpg' %}" alt="feature-cate1">
					<h5>Apartment for rent</h5>
				</div>
				<div class="col-lg-3 col-md-6 f-cata">
					<img src="{% static 'img/feature-cate/2.jpg' %}" alt="">
					<h5>Family Home</h5>
				</div>
				<div class="col-lg-3 col-md-6 f-cata">
					<img src="{% static 'img/feature-cate/3.jpg' %}" alt="">
					<h5>Resort Villas</h5>
				</div>
				<div class="col-lg-3 col-md-6 f-cata">
					<img src="{% static 'img/feature-cate/4.jpg' %}" alt="">
					<h5>Office Building</h5>
				</div>
			</div>
		</div>
	</section>
	<!-- feature category section end-->

templates/filter_form.html
{% load static %}
<!-- Filter form section -->
	<div class="filter-search">
		<div class="container">
			<form class="filter-form" method="get" action="{% url 'search:query' %}">
				<input type="text" placeholder="Enter a street name, address number or keyword" name="q">
				<select>
					<option value="City">City</option>
				</select>
				<select>
					<option value="City">State</option>
				</select>
				<button class="site-btn fs-submit" type="submit">SEARCH</button>
			</form>
		</div>
	</div>
	<!-- Filter form section end -->

templates/footer.html
{% load static %}
<!-- Footer section -->
	<footer class="footer-section set-bg" data-setbg="{% static 'img/footer-bg.jpg' %}">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6 footer-widget">
					<img src="{% static 'img/logo.png' %}" alt="">
					<p>Lorem ipsum dolo sit azmet, consecter dipise consult  elit. Maecenas mamus antesme non anean a dolor sample tempor nuncest erat.</p>
					<div class="social">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-instagram"></i></a>
						<a href="#"><i class="fa fa-pinterest"></i></a>
						<a href="#"><i class="fa fa-linkedin"></i></a>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 footer-widget">
					<div class="contact-widget">
						<h5 class="fw-title">CONTACT US</h5>
						<p><i class="fa fa-map-marker"></i>3711-2880 Nulla St, Mankato, Mississippi </p>
						<p><i class="fa fa-phone"></i>(+88) 666 121 4321</p>
						<p><i class="fa fa-envelope"></i>info.leramiz@colorlib.com</p>
						<p><i class="fa fa-clock-o"></i>Mon - Sat, 08 AM - 06 PM</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6 footer-widget">
					<div class="double-menu-widget">
						<h5 class="fw-title">POPULAR PLACES</h5>
						<ul>
							<li><a href="">Florida</a></li>
							<li><a href="">New York</a></li>
							<li><a href="">Washington</a></li>
							<li><a href="">Los Angeles</a></li>
							<li><a href="">Chicago</a></li>
						</ul>
						<ul>
							<li><a href="">St Louis</a></li>
							<li><a href="">Jacksonville</a></li>
							<li><a href="">San Jose</a></li>
							<li><a href="">San Diego</a></li>
							<li><a href="">Houston</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6  footer-widget">
					<div class="newslatter-widget">
						<h5 class="fw-title">NEWSLETTER</h5>
						<p>Subscribe your email to get the latest news and new offer also discount</p>
						<form class="footer-newslatter-form">
							<input type="text" placeholder="Email address">
							<button><i class="fa fa-send"></i></button>
						</form>
					</div>
				</div>
			</div>
			<div class="footer-bottom">
				<div class="footer-nav">
					<ul>
						<li><a href="">Home</a></li>
						<li><a href="">Featured Listing</a></li>
						<li><a href="">About us</a></li>
						<li><a href="">Pages</a></li>
						<li><a href="">Blog</a></li>
						<li><a href="">Contact</a></li>
					</ul>
				</div>
				<div class="copyright">
					<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer section end -->

templates/gallery.html
{% load static %}
<!-- Gallery section -->
	<section class="gallery-section spad">
		<div class="container">
			<div class="section-title text-center">
				<h3>Popular Places</h3>
				<p>We understand the value and importance of place</p>
			</div>
			<div class="gallery">
				<div class="grid-sizer"></div>
				<a href="#" class="gallery-item grid-long set-bg" data-setbg="{% static 'img/gallery/1.jpg' %}">
					<div class="gi-info">
						<h3>New York</h3>
						<p>118 Properties</p>
					</div>
				</a>
				<a href="#" class="gallery-item grid-wide set-bg" data-setbg="{% static 'img/gallery/2.jpg' %}">
					<div class="gi-info">
						<h3>Florida</h3>
						<p>112 Properties</p>
					</div>
				</a>
				<a href="#" class="gallery-item set-bg" data-setbg="{% static 'img/gallery/3.jpg' %}">
					<div class="gi-info">
						<h3>San Jose</h3>
						<p>72 Properties</p>
					</div>
				</a>
				<a href="#" class="gallery-item set-bg" data-setbg="{% static 'img/gallery/4.jpg' %}">
					<div class="gi-info">
						<h3>St Louis</h3>
						<p>50 Properties</p>
					</div>
				</a>

			</div>
		</div>
	</section>
	<!-- Gallery section end -->

templates/header.html
{% load static %}
<!-- Header section -->
	<header class="header-section">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 header-top-left">
						<div class="top-info">
							<i class="fa fa-phone"></i>
							(+88) 666 121 4321
						</div>
						<div class="top-info">
							<i class="fa fa-envelope"></i>
							info.leramiz@colorlib.com
						</div>
					</div>
					<div class="col-lg-6 text-lg-right header-top-right">
						<div class="top-social">
							<a href=""><i class="fa fa-facebook"></i></a>
							<a href=""><i class="fa fa-twitter"></i></a>
							<a href=""><i class="fa fa-instagram"></i></a>
							<a href=""><i class="fa fa-pinterest"></i></a>
							<a href=""><i class="fa fa-linkedin"></i></a>
						</div>
						<div class="user-panel">
							<a href="{% url 'accounts:register' %}"><i class="fa fa-user-circle-o"></i> Register</a>
							<a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i> Login</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="site-navbar">
						<a href="{% url 'index' %}" class="site-logo"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
						<div class="nav-switch">
							<i class="fa fa-bars"></i>
						</div>
						<ul class="main-menu">
							<li><a href="{% url 'index' %}">Home</a></li>
							<li><a href="{% url 'featured_listing:categories' %}">FEATURED LISTING</a></li>
							<li><a href="{% url 'about:about' %}">ABOUT US</a></li>
							<li><a href="{% url 'featured_listing:categories' %}">Pages</a></li>
							<li><a href="{% url 'blog:blog' %}">Blog</a></li>
							<li><a href="{% url 'contact:contact' %}">Contact</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</header>
	<!-- Header section end -->

templates/hero.html
{% load static %}
<!-- Hero section -->
	<section class="hero-section set-bg" data-setbg="{% static 'img/bg.jpg' %}" style="background-image:url('{% static 'img/bg.jpg'%}')">
		<div class="container hero-text text-white">
			<h2>find your place with our local life style</h2>
			<p>Search real estate property records, houses, condos, land and more on leramiz.com®.<br>Find property info from the most comprehensive source data.</p>
			<a href="#" class="site-btn">VIEW DETAIL</a>
		</div>
	</section>
	<!-- Hero section end -->

templates/services.html
{% load static %}
<!-- Services section -->
	<section class="services-section spad set-bg" data-setbg="{% static 'img/service-bg.jpg' %}">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<img src="{% static 'img/service.jpg' %}" alt="">
				</div>
				<div class="col-lg-5 offset-lg-1 pl-lg-0">
					<div class="section-title text-white">
						<h3>OUR SERVICES</h3>
						<p>We provide the perfect service for </p>
					</div>
					<div class="services">
						<div class="service-item">
							<i class="fa fa-comments"></i>
							<div class="service-text">
								<h5>Consultant Service</h5>
								<p>In Aenean purus, pretium sito amet sapien denim consectet sed urna placerat sodales magna leo.</p>
							</div>
						</div>
						<div class="service-item">
							<i class="fa fa-home"></i>
							<div class="service-text">
								<h5>Properties Management</h5>
								<p>In Aenean purus, pretium sito amet sapien denim consectet sed urna placerat sodales magna leo.</p>
							</div>
						</div>
						<div class="service-item">
							<i class="fa fa-briefcase"></i>
							<div class="service-text">
								<h5>Renting and Selling</h5>
								<p>In Aenean purus, pretium sito amet sapien denim consectet sed urna placerat sodales magna leo.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Services section end -->